/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e8611528763035aac7a59c3
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import EyesActions from "../redux/actions/EyesActions";
import FaceActions from "../redux/actions/FaceActions";

// END IMPORT ACTIONS

/** APIs

* actionsEyes.create
*	@description CRUD ACTION create
*
* actionsEyes.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsEyes.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsFace.list
*	@description CRUD ACTION list
*

**/

class EyesEdit extends Component {
  // Init eyes
  constructor(props) {
    super(props);
    this.state = {
      eyes: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsEyes.loadEyes(this.props.match.params.id);
      this.props.actionsMan.findByeyes(this.props.match.params.id);
    }
    
    this.props.actionsFace.loadFaceList();
  }

  // Insert props eyes in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      eyes: props.eyes
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.eyes._id) {
      this.props.actionsEyes.saveEyes(this.state.eyes).then(data => {
        this.props.history.push("/eyeses/");
      });
    } else {
      this.props.actionsEyes.createEyes(this.state.eyes).then(data => {
        this.props.history.push("/eyeses/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Eyes Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="color"
            label="Color"
            value={this.state.eyes.color || ""}
            onChange={Utils.handleChange.bind(this, "eyes")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="type"
            label="Type"
            value={this.state.eyes.type || ""}
            onChange={Utils.handleChange.bind(this, "eyes")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m eyes with Face */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="eyes">
              Eyes
            </InputLabel>
            <Select
              value={this.state.eyes.eyes || ""}
              onChange={Utils.handleChangeSelect.bind(this, "eyes")}
              inputProps={{
                id: "eyes",
                name: "eyes"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listFace && this.props.listFace.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with man */}
          
          <h3>Man</h3>
          {(!this.props.listMan || this.props.listMan.length === 0) && 
            <div>No Man associated</div>
          }
          {this.props.listMan &&
            this.props.listMan.map((item, i) => {
              return (
                <Link to={"/mans/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/eyeses/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsEyes: bindActionCreators(EyesActions, dispatch),
    actionsFace: bindActionCreators(FaceActions, dispatch),
  };
};

// Validate types
EyesEdit.propTypes = { 
  actionsEyes: PropTypes.object.isRequired,
  actionsFace: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    eyes: state.EyesEditReducer.eyes,
    listFace: state.EyesEditReducer.listFace,
    listMan: state.EyesEditReducer.listMan
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(EyesEdit);
