/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e8611528763035aac7a59c3
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Switch from "@material-ui/core/Switch";
import FormControlLabel from "@material-ui/core/FormControlLabel";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import FaceActions from "../redux/actions/FaceActions";
import EyesActions from "../redux/actions/EyesActions";
import EarsActions from "../redux/actions/EarsActions";

// END IMPORT ACTIONS

/** APIs

* actionsFace.create
*	@description CRUD ACTION create
*
* actionsFace.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsFace.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsUser.list
*	@description CRUD ACTION list
*
* actionsEyes.findByeyes
*	@description CRUD ACTION findByeyes
*	@param Objectid key - Id of model to search for
*
* actionsEars.findByears
*	@description CRUD ACTION findByears
*	@param Objectid key - Id of model to search for
*

**/

class FaceEdit extends Component {
  // Init face
  constructor(props) {
    super(props);
    this.state = {
      face: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsFace.loadFace(this.props.match.params.id);
      this.props.actionsEars.findByears(this.props.match.params.id);
      this.props.actionsEyes.findByeyes(this.props.match.params.id);
      this.props.actionsMan.findByface(this.props.match.params.id);
    }
    
    this.props.actionsUser.loadUserList();
  }

  // Insert props face in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      face: props.face
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.face._id) {
      this.props.actionsFace.saveFace(this.state.face).then(data => {
        this.props.history.push("/faces/");
      });
    } else {
      this.props.actionsFace.createFace(this.state.face).then(data => {
        this.props.history.push("/faces/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Face Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="ears"
            label="Ears"
            value={this.state.face.ears || ""}
            onChange={Utils.handleChange.bind(this, "face")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="eyesnum"
            label="Eyesnum"
            value={this.state.face.eyesnum || ""}
            onChange={Utils.handleChange.bind(this, "face")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          <FormControlLabel
            control={
              <Switch
                id="mouth"
                checked={this.state.face.mouth || false}
                onChange={Utils.handleChangeCheck.bind(this, "face", "mouth")}
                color="primary"
              />
            }
            label="mouth"
            className="mt-20"
          />
          
          <FormControlLabel
            control={
              <Switch
                id="nose"
                checked={this.state.face.nose || false}
                onChange={Utils.handleChangeCheck.bind(this, "face", "nose")}
                color="primary"
              />
            }
            label="nose"
            className="mt-20"
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation m:m relation with User */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="relation">Relation</InputLabel>
            <Select
              multiple
              value={this.state.face.relation || []}
              onChange={Utils.handleChangeSelect.bind(this, "face")}
              input={<Input id="relation" name="relation" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listUser && this.props.listUser.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.face.relation &&
                      this.state.face.relation.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with ears */}
          
          <h3>Ears</h3>
          {(!this.props.listEars || this.props.listEars.length === 0) && 
            <div>No Ears associated</div>
          }
          {this.props.listEars &&
            this.props.listEars.map((item, i) => {
              return (
                <Link to={"/earss/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with eyes */}
          
          <h3>Eyes</h3>
          {(!this.props.listEyes || this.props.listEyes.length === 0) && 
            <div>No Eyes associated</div>
          }
          {this.props.listEyes &&
            this.props.listEyes.map((item, i) => {
              return (
                <Link to={"/eyess/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with man */}
          
          <h3>Man</h3>
          {(!this.props.listMan || this.props.listMan.length === 0) && 
            <div>No Man associated</div>
          }
          {this.props.listMan &&
            this.props.listMan.map((item, i) => {
              return (
                <Link to={"/mans/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/faces/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsFace: bindActionCreators(FaceActions, dispatch),
    actionsEyes: bindActionCreators(EyesActions, dispatch),
    actionsEars: bindActionCreators(EarsActions, dispatch),
  };
};

// Validate types
FaceEdit.propTypes = { 
  actionsFace: PropTypes.object.isRequired,
  actionsEyes: PropTypes.object.isRequired,
  actionsEars: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    face: state.FaceEditReducer.face,
    listUser: state.FaceEditReducer.listUser,
    listEars: state.FaceEditReducer.listEars,
    listEyes: state.FaceEditReducer.listEyes,
    listMan: state.FaceEditReducer.listMan
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(FaceEdit);
