/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e8611528763035aac7a59c3
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// FACE
export const CREATE_FACE_SUCCESS = "CREATE_FACE_SUCCESS";
export const DELETE_FACE_SUCCESS = "DELETE_FACE_SUCCESS";
export const GET_FACE_SUCCESS = "GET_FACE_SUCCESS";
export const LIST_FACE_SUCCESS = "LIST_FACE_SUCCESS";
export const UPDATE_FACE_SUCCESS = "UPDATE_FACE_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// EARS
export const CREATE_EARS_SUCCESS = "CREATE_EARS_SUCCESS";
export const DELETE_EARS_SUCCESS = "DELETE_EARS_SUCCESS";
export const FINDBYEARS_EARS_SUCCESS = "FINDBYEARS_EARS_SUCCESS";
export const GET_EARS_SUCCESS = "GET_EARS_SUCCESS";
export const LIST_EARS_SUCCESS = "LIST_EARS_SUCCESS";
export const UPDATE_EARS_SUCCESS = "UPDATE_EARS_SUCCESS";

// EYES
export const CREATE_EYES_SUCCESS = "CREATE_EYES_SUCCESS";
export const DELETE_EYES_SUCCESS = "DELETE_EYES_SUCCESS";
export const FINDBYEYES_EYES_SUCCESS = "FINDBYEYES_EYES_SUCCESS";
export const GET_EYES_SUCCESS = "GET_EYES_SUCCESS";
export const LIST_EYES_SUCCESS = "LIST_EYES_SUCCESS";
export const UPDATE_EYES_SUCCESS = "UPDATE_EYES_SUCCESS";

// MAN
export const CREATE_MAN_SUCCESS = "CREATE_MAN_SUCCESS";
export const DELETE_MAN_SUCCESS = "DELETE_MAN_SUCCESS";
export const GET_MAN_SUCCESS = "GET_MAN_SUCCESS";
export const LIST_MAN_SUCCESS = "LIST_MAN_SUCCESS";
export const UPDATE_MAN_SUCCESS = "UPDATE_MAN_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
